/** Static metadata generated by prep_data.py */
export interface Metadata {
  congress_min: number;
  congress_max: number;
  congresses: number[];
  member_count: number;
  caucus_count: number;
  membership_count: number;
  has_nominate: number[];
  derived_tables?: string[];
}

let _cache: Metadata | null = null;

export async function loadMetadata(): Promise<Metadata> {
  if (_cache) return _cache;
  const res = await fetch('/data/metadata.json');
  if (!res.ok) throw new Error(`Failed to load metadata: ${res.status}`);
  _cache = (await res.json()) as Metadata;
  return _cache;
}
